// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const accountByID = `-- name: AccountByID :one
SELECT id, user_id, name, type, currency, institution, opening_balance_cents, is_archived, created_at FROM accounts WHERE id = $2 AND user_id = $1
`

type AccountByIDParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) AccountByID(ctx context.Context, arg AccountByIDParams) (Account, error) {
	row := q.db.QueryRow(ctx, accountByID, arg.UserID, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Institution,
		&i.OpeningBalanceCents,
		&i.IsArchived,
		&i.CreatedAt,
	)
	return i, err
}

const countAccountTransactions = `-- name: CountAccountTransactions :one
SELECT count(*) FROM transactions WHERE account_id = $2 AND user_id = $1
`

type CountAccountTransactionsParams struct {
	UserID    uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) CountAccountTransactions(ctx context.Context, arg CountAccountTransactionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAccountTransactions, arg.UserID, arg.AccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (user_id, name, type, currency, institution, opening_balance_cents)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, type, currency, institution, opening_balance_cents, is_archived, created_at
`

type CreateAccountParams struct {
	UserID              uuid.UUID
	Name                string
	Type                AccountType
	Currency            string
	Institution         string
	OpeningBalanceCents int64
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.Institution,
		arg.OpeningBalanceCents,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Institution,
		&i.OpeningBalanceCents,
		&i.IsArchived,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :execrows
DELETE FROM accounts WHERE id = $2 AND user_id = $1
`

type DeleteAccountParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccount, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAccounts = `-- name: ListAccounts :many
SELECT a.id, a.user_id, a.name, a.type, a.currency, a.institution, a.opening_balance_cents, a.is_archived, a.created_at,
       CASE WHEN a.type IN ('rrsp', 'tfsa', 'fhsa', 'non_registered')
            THEN coalesce(s.balance_cents, 0)
            ELSE a.opening_balance_cents + coalesce(t.sum_cents, 0)
       END::bigint AS balance_cents
FROM accounts a
LEFT JOIN LATERAL (
    SELECT bs.balance_cents FROM balance_snapshots bs
    WHERE bs.account_id = a.id
    ORDER BY bs.as_of DESC LIMIT 1
) s ON true
LEFT JOIN LATERAL (
    SELECT sum(tx.amount_cents) AS sum_cents FROM transactions tx
    WHERE tx.account_id = a.id
) t ON true
WHERE a.user_id = $1
ORDER BY a.is_archived, a.created_at
`

type ListAccountsRow struct {
	Account      Account
	BalanceCents int64
}

// Balance is derived per account kind: investment-style accounts use the
// latest snapshot, cash accounts sum their transactions on top of the
// opening balance.
func (q *Queries) ListAccounts(ctx context.Context, userID uuid.UUID) ([]ListAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsRow
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.Account.ID,
			&i.Account.UserID,
			&i.Account.Name,
			&i.Account.Type,
			&i.Account.Currency,
			&i.Account.Institution,
			&i.Account.OpeningBalanceCents,
			&i.Account.IsArchived,
			&i.Account.CreatedAt,
			&i.BalanceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = $3, type = $4, currency = $5, institution = $6,
    opening_balance_cents = $7, is_archived = $8
WHERE id = $2 AND user_id = $1
RETURNING id, user_id, name, type, currency, institution, opening_balance_cents, is_archived, created_at
`

type UpdateAccountParams struct {
	UserID              uuid.UUID
	ID                  uuid.UUID
	Name                string
	Type                AccountType
	Currency            string
	Institution         string
	OpeningBalanceCents int64
	IsArchived          bool
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.UserID,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.Institution,
		arg.OpeningBalanceCents,
		arg.IsArchived,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Institution,
		&i.OpeningBalanceCents,
		&i.IsArchived,
		&i.CreatedAt,
	)
	return i, err
}
