// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const categoryByID = `-- name: CategoryByID :one
SELECT id, user_id, name, kind, color, is_archived, created_at FROM categories WHERE id = $2 AND user_id = $1
`

type CategoryByIDParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) CategoryByID(ctx context.Context, arg CategoryByIDParams) (Category, error) {
	row := q.db.QueryRow(ctx, categoryByID, arg.UserID, arg.ID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Kind,
		&i.Color,
		&i.IsArchived,
		&i.CreatedAt,
	)
	return i, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (user_id, name, kind, color)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, kind, color, is_archived, created_at
`

type CreateCategoryParams struct {
	UserID uuid.UUID
	Name   string
	Kind   CategoryKind
	Color  string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.UserID,
		arg.Name,
		arg.Kind,
		arg.Color,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Kind,
		&i.Color,
		&i.IsArchived,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM categories WHERE id = $2 AND user_id = $1
`

type DeleteCategoryParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

// Transactions referencing the category go uncategorized via ON DELETE SET NULL.
func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategory, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, user_id, name, kind, color, is_archived, created_at FROM categories WHERE user_id = $1 ORDER BY kind, is_archived, name
`

func (q *Queries) ListCategories(ctx context.Context, userID uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Kind,
			&i.Color,
			&i.IsArchived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignCategory = `-- name: ReassignCategory :execrows
UPDATE transactions SET category_id = $3, updated_at = now()
WHERE transactions.user_id = $1 AND transactions.category_id = $2
  AND EXISTS (SELECT 1 FROM categories c WHERE c.id = $3 AND c.user_id = $1)
`

type ReassignCategoryParams struct {
	UserID       uuid.UUID
	CategoryID   *uuid.UUID
	CategoryID_2 *uuid.UUID
}

// Moves all transactions from one category to another (both owned by the
// user; the target check is the WHERE EXISTS guard).
func (q *Queries) ReassignCategory(ctx context.Context, arg ReassignCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, reassignCategory, arg.UserID, arg.CategoryID, arg.CategoryID_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const seedDefaultCategories = `-- name: SeedDefaultCategories :exec
INSERT INTO categories (user_id, name, kind, color)
SELECT $1, unnest($2::text[]), unnest($3::text[])::category_kind, unnest($4::text[])
ON CONFLICT DO NOTHING
`

type SeedDefaultCategoriesParams struct {
	UserID uuid.UUID
	Names  []string
	Kinds  []string
	Colors []string
}

// Bulk-inserts the default category set for a new user (called inside the
// user-create transaction).
func (q *Queries) SeedDefaultCategories(ctx context.Context, arg SeedDefaultCategoriesParams) error {
	_, err := q.db.Exec(ctx, seedDefaultCategories,
		arg.UserID,
		arg.Names,
		arg.Kinds,
		arg.Colors,
	)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $3, color = $4, is_archived = $5
WHERE id = $2 AND user_id = $1
RETURNING id, user_id, name, kind, color, is_archived, created_at
`

type UpdateCategoryParams struct {
	UserID     uuid.UUID
	ID         uuid.UUID
	Name       string
	Color      string
	IsArchived bool
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.UserID,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.IsArchived,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Kind,
		&i.Color,
		&i.IsArchived,
		&i.CreatedAt,
	)
	return i, err
}
