// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contributions.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const contributionTotals = `-- name: ContributionTotals :many
SELECT a.type AS account_type,
       coalesce(sum(t.amount_cents) FILTER (WHERE t.amount_cents > 0), 0)::bigint AS contributed_cents,
       coalesce(-sum(t.amount_cents) FILTER (WHERE t.amount_cents < 0), 0)::bigint AS withdrawn_cents
FROM transactions t
JOIN accounts a ON a.id = t.account_id
WHERE t.user_id = $1
  AND a.type IN ('rrsp', 'tfsa', 'fhsa')
  AND t.date >= make_date($2, 1, 1)
  AND t.date < make_date($2 + 1, 1, 1)
  AND NOT EXISTS (
      SELECT 1 FROM transactions peer
      JOIN accounts pa ON pa.id = peer.account_id
      WHERE peer.transfer_group_id = t.transfer_group_id
        AND peer.id <> t.id
        AND pa.type = a.type)
GROUP BY a.type
`

type ContributionTotalsParams struct {
	UserID uuid.UUID
	Year   int32
}

type ContributionTotalsRow struct {
	AccountType      AccountType
	ContributedCents int64
	WithdrawnCents   int64
}

// Calendar-year contributions and withdrawals per registered account type,
// derived from transactions. Transfers between two accounts of the SAME
// type (e.g. TFSA -> TFSA) are excluded - moving money within a type is not
// a new contribution - while cross-type transfers (chequing -> TFSA) count.
func (q *Queries) ContributionTotals(ctx context.Context, arg ContributionTotalsParams) ([]ContributionTotalsRow, error) {
	rows, err := q.db.Query(ctx, contributionTotals, arg.UserID, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContributionTotalsRow
	for rows.Next() {
		var i ContributionTotalsRow
		if err := rows.Scan(&i.AccountType, &i.ContributedCents, &i.WithdrawnCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContributionRoom = `-- name: ListContributionRoom :many
SELECT id, user_id, account_type, tax_year, room_cents, notes FROM contribution_room WHERE user_id = $1 AND tax_year = $2
`

type ListContributionRoomParams struct {
	UserID  uuid.UUID
	TaxYear int32
}

func (q *Queries) ListContributionRoom(ctx context.Context, arg ListContributionRoomParams) ([]ContributionRoom, error) {
	rows, err := q.db.Query(ctx, listContributionRoom, arg.UserID, arg.TaxYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContributionRoom
	for rows.Next() {
		var i ContributionRoom
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountType,
			&i.TaxYear,
			&i.RoomCents,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertContributionRoom = `-- name: UpsertContributionRoom :one
INSERT INTO contribution_room (user_id, account_type, tax_year, room_cents, notes)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, account_type, tax_year)
DO UPDATE SET room_cents = EXCLUDED.room_cents, notes = EXCLUDED.notes
RETURNING id, user_id, account_type, tax_year, room_cents, notes
`

type UpsertContributionRoomParams struct {
	UserID      uuid.UUID
	AccountType AccountType
	TaxYear     int32
	RoomCents   int64
	Notes       string
}

func (q *Queries) UpsertContributionRoom(ctx context.Context, arg UpsertContributionRoomParams) (ContributionRoom, error) {
	row := q.db.QueryRow(ctx, upsertContributionRoom,
		arg.UserID,
		arg.AccountType,
		arg.TaxYear,
		arg.RoomCents,
		arg.Notes,
	)
	var i ContributionRoom
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountType,
		&i.TaxYear,
		&i.RoomCents,
		&i.Notes,
	)
	return i, err
}
