// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: imports.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createImportBatch = `-- name: CreateImportBatch :one
INSERT INTO import_batches (user_id, account_id, filename, mapping, row_count, imported_count, skipped_count)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, account_id, filename, mapping, row_count, imported_count, skipped_count, created_at
`

type CreateImportBatchParams struct {
	UserID        uuid.UUID
	AccountID     uuid.UUID
	Filename      string
	Mapping       []byte
	RowCount      int32
	ImportedCount int32
	SkippedCount  int32
}

func (q *Queries) CreateImportBatch(ctx context.Context, arg CreateImportBatchParams) (ImportBatch, error) {
	row := q.db.QueryRow(ctx, createImportBatch,
		arg.UserID,
		arg.AccountID,
		arg.Filename,
		arg.Mapping,
		arg.RowCount,
		arg.ImportedCount,
		arg.SkippedCount,
	)
	var i ImportBatch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Filename,
		&i.Mapping,
		&i.RowCount,
		&i.ImportedCount,
		&i.SkippedCount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteImportBatch = `-- name: DeleteImportBatch :execrows
DELETE FROM import_batches WHERE id = $2 AND user_id = $1
`

type DeleteImportBatchParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

// Reverting an import: the transactions FK cascades, removing its rows.
func (q *Queries) DeleteImportBatch(ctx context.Context, arg DeleteImportBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteImportBatch, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const latestMappingForAccount = `-- name: LatestMappingForAccount :one
SELECT mapping FROM import_batches
WHERE user_id = $1 AND account_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type LatestMappingForAccountParams struct {
	UserID    uuid.UUID
	AccountID uuid.UUID
}

// The last mapping used for an account prefills the next import.
func (q *Queries) LatestMappingForAccount(ctx context.Context, arg LatestMappingForAccountParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, latestMappingForAccount, arg.UserID, arg.AccountID)
	var mapping []byte
	err := row.Scan(&mapping)
	return mapping, err
}

const listImportBatches = `-- name: ListImportBatches :many
SELECT b.id, b.user_id, b.account_id, b.filename, b.mapping, b.row_count, b.imported_count, b.skipped_count, b.created_at, a.name AS account_name
FROM import_batches b
JOIN accounts a ON a.id = b.account_id
WHERE b.user_id = $1
ORDER BY b.created_at DESC
`

type ListImportBatchesRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	AccountID     uuid.UUID
	Filename      string
	Mapping       []byte
	RowCount      int32
	ImportedCount int32
	SkippedCount  int32
	CreatedAt     time.Time
	AccountName   string
}

func (q *Queries) ListImportBatches(ctx context.Context, userID uuid.UUID) ([]ListImportBatchesRow, error) {
	rows, err := q.db.Query(ctx, listImportBatches, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListImportBatchesRow
	for rows.Next() {
		var i ListImportBatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Filename,
			&i.Mapping,
			&i.RowCount,
			&i.ImportedCount,
			&i.SkippedCount,
			&i.CreatedAt,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
