// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type AccountType string

const (
	AccountTypeChequing      AccountType = "chequing"
	AccountTypeSavings       AccountType = "savings"
	AccountTypeCreditCard    AccountType = "credit_card"
	AccountTypeRrsp          AccountType = "rrsp"
	AccountTypeTfsa          AccountType = "tfsa"
	AccountTypeFhsa          AccountType = "fhsa"
	AccountTypeNonRegistered AccountType = "non_registered"
	AccountTypeOther         AccountType = "other"
)

func (e *AccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountType(s)
	case string:
		*e = AccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountType: %T", src)
	}
	return nil
}

type NullAccountType struct {
	AccountType AccountType
	Valid       bool // Valid is true if AccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.AccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountType), nil
}

type CategoryKind string

const (
	CategoryKindIncome  CategoryKind = "income"
	CategoryKindExpense CategoryKind = "expense"
)

func (e *CategoryKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CategoryKind(s)
	case string:
		*e = CategoryKind(s)
	default:
		return fmt.Errorf("unsupported scan type for CategoryKind: %T", src)
	}
	return nil
}

type NullCategoryKind struct {
	CategoryKind CategoryKind
	Valid        bool // Valid is true if CategoryKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCategoryKind) Scan(value interface{}) error {
	if value == nil {
		ns.CategoryKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CategoryKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCategoryKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CategoryKind), nil
}

type Account struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	Name                string
	Type                AccountType
	Currency            string
	Institution         string
	OpeningBalanceCents int64
	IsArchived          bool
	CreatedAt           time.Time
}

type BalanceSnapshot struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	AccountID    uuid.UUID
	AsOf         time.Time
	BalanceCents int64
	CreatedAt    time.Time
}

type Category struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	Kind       CategoryKind
	Color      string
	IsArchived bool
	CreatedAt  time.Time
}

type ContributionRoom struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	AccountType AccountType
	TaxYear     int32
	RoomCents   int64
	Notes       string
}

type ImportBatch struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	AccountID     uuid.UUID
	Filename      string
	Mapping       []byte
	RowCount      int32
	ImportedCount int32
	SkippedCount  int32
	CreatedAt     time.Time
}

type Session struct {
	TokenHash  []byte
	UserID     uuid.UUID
	CreatedAt  time.Time
	ExpiresAt  time.Time
	LastSeenAt time.Time
}

type Transaction struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	AccountID       uuid.UUID
	Date            time.Time
	AmountCents     int64
	Payee           string
	Notes           string
	CategoryID      *uuid.UUID
	TransferGroupID *uuid.UUID
	ImportBatchID   *uuid.UUID
	DedupHash       []byte
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	DisplayName  string
	AvatarURL    *string
	GoogleSub    *string
	OidcSub      *string
	PasswordHash *string
	IsAdmin      bool
	CreatedAt    time.Time
}
