// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const reportCategoryTotals = `-- name: ReportCategoryTotals :many
SELECT c.id AS category_id,
       coalesce(c.name, 'Uncategorized') AS category_name,
       c.kind AS category_kind,
       coalesce(c.color, '') AS category_color,
       coalesce(sum(t.amount_cents) FILTER (WHERE t.amount_cents > 0), 0)::bigint AS inflow_cents,
       coalesce(-sum(t.amount_cents) FILTER (WHERE t.amount_cents < 0), 0)::bigint AS outflow_cents
FROM transactions t
LEFT JOIN categories c ON c.id = t.category_id
WHERE t.user_id = $1 AND t.date >= $2 AND t.date <= $3
  AND t.transfer_group_id IS NULL
GROUP BY c.id, c.name, c.kind, c.color
`

type ReportCategoryTotalsParams struct {
	UserID uuid.UUID
	Date   time.Time
	Date_2 time.Time
}

type ReportCategoryTotalsRow struct {
	CategoryID    *uuid.UUID
	CategoryName  string
	CategoryKind  *CategoryKind
	CategoryColor string
	InflowCents   int64
	OutflowCents  int64
}

// Net flow per category over a range (transfers excluded). Feeds the Sankey
// and the category breakdown. Uncategorized rows come back with a NULL
// category id; the server buckets them by sign.
func (q *Queries) ReportCategoryTotals(ctx context.Context, arg ReportCategoryTotalsParams) ([]ReportCategoryTotalsRow, error) {
	rows, err := q.db.Query(ctx, reportCategoryTotals, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportCategoryTotalsRow
	for rows.Next() {
		var i ReportCategoryTotalsRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryKind,
			&i.CategoryColor,
			&i.InflowCents,
			&i.OutflowCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportNetWorth = `-- name: ReportNetWorth :many
SELECT m.month::date AS month,
       a.type AS account_type,
       sum(s.balance_cents)::bigint AS total_cents
FROM generate_series(date_trunc('month', $2::date), date_trunc('month', $3::date), interval '1 month') AS m(month)
CROSS JOIN accounts a
JOIN LATERAL (
    SELECT bs.balance_cents
    FROM balance_snapshots bs
    WHERE bs.account_id = a.id
      AND bs.as_of < (m.month + interval '1 month')
    ORDER BY bs.as_of DESC
    LIMIT 1
) s ON true
WHERE a.user_id = $1 AND NOT a.is_archived
GROUP BY 1, a.type
ORDER BY 1
`

type ReportNetWorthParams struct {
	UserID  uuid.UUID
	Column2 time.Time
	Column3 time.Time
}

type ReportNetWorthRow struct {
	Month       time.Time
	AccountType AccountType
	TotalCents  int64
}

// Month-end net worth per account type: for each month in the range, carry
// forward the latest snapshot on or before month end for every unarchived
// account, and sum by type. Months before an account's first snapshot
// contribute nothing.
func (q *Queries) ReportNetWorth(ctx context.Context, arg ReportNetWorthParams) ([]ReportNetWorthRow, error) {
	rows, err := q.db.Query(ctx, reportNetWorth, arg.UserID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportNetWorthRow
	for rows.Next() {
		var i ReportNetWorthRow
		if err := rows.Scan(&i.Month, &i.AccountType, &i.TotalCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportSummary = `-- name: ReportSummary :one
SELECT
    coalesce(sum(t.amount_cents) FILTER (WHERE t.amount_cents > 0), 0)::bigint AS income_cents,
    coalesce(-sum(t.amount_cents) FILTER (WHERE t.amount_cents < 0), 0)::bigint AS expense_cents,
    count(*) FILTER (WHERE t.category_id IS NULL)::bigint AS uncategorized_count
FROM transactions t
WHERE t.user_id = $1 AND t.date >= $2 AND t.date <= $3
  AND t.transfer_group_id IS NULL
`

type ReportSummaryParams struct {
	UserID uuid.UUID
	Date   time.Time
	Date_2 time.Time
}

type ReportSummaryRow struct {
	IncomeCents        int64
	ExpenseCents       int64
	UncategorizedCount int64
}

// Dashboard tiles for a date range. Income/expense are sign-based over
// non-transfer transactions, so uncategorized rows still count.
func (q *Queries) ReportSummary(ctx context.Context, arg ReportSummaryParams) (ReportSummaryRow, error) {
	row := q.db.QueryRow(ctx, reportSummary, arg.UserID, arg.Date, arg.Date_2)
	var i ReportSummaryRow
	err := row.Scan(&i.IncomeCents, &i.ExpenseCents, &i.UncategorizedCount)
	return i, err
}

const reportTrends = `-- name: ReportTrends :many
SELECT date_trunc('month', t.date)::date AS month,
       c.id AS category_id,
       coalesce(c.name, 'Uncategorized') AS category_name,
       c.kind AS category_kind,
       coalesce(c.color, '') AS category_color,
       coalesce(sum(t.amount_cents) FILTER (WHERE t.amount_cents > 0), 0)::bigint AS inflow_cents,
       coalesce(-sum(t.amount_cents) FILTER (WHERE t.amount_cents < 0), 0)::bigint AS outflow_cents
FROM transactions t
LEFT JOIN categories c ON c.id = t.category_id
WHERE t.user_id = $1 AND t.date >= $2 AND t.date <= $3
  AND t.transfer_group_id IS NULL
GROUP BY 1, c.id, c.name, c.kind, c.color
ORDER BY 1
`

type ReportTrendsParams struct {
	UserID uuid.UUID
	Date   time.Time
	Date_2 time.Time
}

type ReportTrendsRow struct {
	Month         time.Time
	CategoryID    *uuid.UUID
	CategoryName  string
	CategoryKind  *CategoryKind
	CategoryColor string
	InflowCents   int64
	OutflowCents  int64
}

// Monthly net flow per category (transfers excluded) for trend charts.
func (q *Queries) ReportTrends(ctx context.Context, arg ReportTrendsParams) ([]ReportTrendsRow, error) {
	rows, err := q.db.Query(ctx, reportTrends, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportTrendsRow
	for rows.Next() {
		var i ReportTrendsRow
		if err := rows.Scan(
			&i.Month,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryKind,
			&i.CategoryColor,
			&i.InflowCents,
			&i.OutflowCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
