// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snapshots.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteSnapshot = `-- name: DeleteSnapshot :execrows
DELETE FROM balance_snapshots WHERE id = $2 AND user_id = $1
`

type DeleteSnapshotParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteSnapshot(ctx context.Context, arg DeleteSnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSnapshot, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listSnapshots = `-- name: ListSnapshots :many
SELECT id, user_id, account_id, as_of, balance_cents, created_at FROM balance_snapshots
WHERE user_id = $1 AND account_id = $2
ORDER BY as_of DESC
`

type ListSnapshotsParams struct {
	UserID    uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) ListSnapshots(ctx context.Context, arg ListSnapshotsParams) ([]BalanceSnapshot, error) {
	rows, err := q.db.Query(ctx, listSnapshots, arg.UserID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BalanceSnapshot
	for rows.Next() {
		var i BalanceSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.AsOf,
			&i.BalanceCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSnapshot = `-- name: UpsertSnapshot :one
INSERT INTO balance_snapshots (user_id, account_id, as_of, balance_cents)
VALUES ($1, $2, $3, $4)
ON CONFLICT (account_id, as_of)
DO UPDATE SET balance_cents = EXCLUDED.balance_cents
RETURNING id, user_id, account_id, as_of, balance_cents, created_at
`

type UpsertSnapshotParams struct {
	UserID       uuid.UUID
	AccountID    uuid.UUID
	AsOf         time.Time
	BalanceCents int64
}

func (q *Queries) UpsertSnapshot(ctx context.Context, arg UpsertSnapshotParams) (BalanceSnapshot, error) {
	row := q.db.QueryRow(ctx, upsertSnapshot,
		arg.UserID,
		arg.AccountID,
		arg.AsOf,
		arg.BalanceCents,
	)
	var i BalanceSnapshot
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.AsOf,
		&i.BalanceCents,
		&i.CreatedAt,
	)
	return i, err
}
