// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countTransactions = `-- name: CountTransactions :one
SELECT count(*)
FROM transactions t
WHERE t.user_id = $1
  AND ($2::date IS NULL OR t.date >= $2)
  AND ($3::date IS NULL OR t.date <= $3)
  AND ($4::uuid IS NULL OR t.account_id = $4)
  AND ($5::uuid IS NULL OR t.category_id = $5)
  AND (NOT $6::boolean OR (t.category_id IS NULL AND t.transfer_group_id IS NULL))
  AND ($7::text = '' OR t.payee ILIKE '%' || $7 || '%' OR t.notes ILIKE '%' || $7 || '%')
`

type CountTransactionsParams struct {
	UserID        uuid.UUID
	FromDate      *time.Time
	ToDate        *time.Time
	AccountID     *uuid.UUID
	CategoryID    *uuid.UUID
	Uncategorized bool
	Search        string
}

func (q *Queries) CountTransactions(ctx context.Context, arg CountTransactionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactions,
		arg.UserID,
		arg.FromDate,
		arg.ToDate,
		arg.AccountID,
		arg.CategoryID,
		arg.Uncategorized,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions
    (user_id, account_id, date, amount_cents, payee, notes, category_id,
     transfer_group_id, import_batch_id, dedup_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, account_id, date, amount_cents, payee, notes, category_id, transfer_group_id, import_batch_id, dedup_hash, created_at, updated_at
`

type CreateTransactionParams struct {
	UserID          uuid.UUID
	AccountID       uuid.UUID
	Date            time.Time
	AmountCents     int64
	Payee           string
	Notes           string
	CategoryID      *uuid.UUID
	TransferGroupID *uuid.UUID
	ImportBatchID   *uuid.UUID
	DedupHash       []byte
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.AccountID,
		arg.Date,
		arg.AmountCents,
		arg.Payee,
		arg.Notes,
		arg.CategoryID,
		arg.TransferGroupID,
		arg.ImportBatchID,
		arg.DedupHash,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Date,
		&i.AmountCents,
		&i.Payee,
		&i.Notes,
		&i.CategoryID,
		&i.TransferGroupID,
		&i.ImportBatchID,
		&i.DedupHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :execrows
DELETE FROM transactions
WHERE transactions.user_id = $1
  AND (transactions.id = $2
       OR (transactions.transfer_group_id IS NOT NULL AND transactions.transfer_group_id = (
             SELECT tg.transfer_group_id FROM transactions tg
             WHERE tg.id = $2 AND tg.user_id = $1)))
`

type DeleteTransactionParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

// Deleting a transfer leg removes both legs; the subquery resolves the group
// (NULL for plain transactions, so only the row itself matches).
func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTransaction, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findByDedupHashes = `-- name: FindByDedupHashes :many
SELECT id, date, amount_cents, payee, dedup_hash
FROM transactions
WHERE user_id = $1 AND account_id = $2 AND dedup_hash = ANY($3::bytea[])
`

type FindByDedupHashesParams struct {
	UserID    uuid.UUID
	AccountID uuid.UUID
	Column3   [][]byte
}

type FindByDedupHashesRow struct {
	ID          uuid.UUID
	Date        time.Time
	AmountCents int64
	Payee       string
	DedupHash   []byte
}

// Existing transactions in an account matching any of the given hashes, for
// soft duplicate warnings during CSV import.
func (q *Queries) FindByDedupHashes(ctx context.Context, arg FindByDedupHashesParams) ([]FindByDedupHashesRow, error) {
	rows, err := q.db.Query(ctx, findByDedupHashes, arg.UserID, arg.AccountID, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindByDedupHashesRow
	for rows.Next() {
		var i FindByDedupHashesRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.AmountCents,
			&i.Payee,
			&i.DedupHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT t.id, t.account_id, t.date, t.amount_cents, t.payee, t.notes,
       t.category_id, t.transfer_group_id, t.import_batch_id,
       t.created_at, t.updated_at,
       c.name AS category_name, c.kind AS category_kind, c.color AS category_color,
       a.name AS account_name, a.type AS account_type, a.currency AS account_currency
FROM transactions t
LEFT JOIN categories c ON c.id = t.category_id
JOIN accounts a ON a.id = t.account_id
WHERE t.user_id = $1
  AND ($2::date IS NULL OR t.date >= $2)
  AND ($3::date IS NULL OR t.date <= $3)
  AND ($4::uuid IS NULL OR t.account_id = $4)
  AND ($5::uuid IS NULL OR t.category_id = $5)
  AND (NOT $6::boolean OR (t.category_id IS NULL AND t.transfer_group_id IS NULL))
  AND ($7::text = '' OR t.payee ILIKE '%' || $7 || '%' OR t.notes ILIKE '%' || $7 || '%')
ORDER BY t.date DESC, t.created_at DESC
LIMIT $9 OFFSET $8
`

type ListTransactionsParams struct {
	UserID        uuid.UUID
	FromDate      *time.Time
	ToDate        *time.Time
	AccountID     *uuid.UUID
	CategoryID    *uuid.UUID
	Uncategorized bool
	Search        string
	RowOffset     int32
	RowLimit      int32
}

type ListTransactionsRow struct {
	ID              uuid.UUID
	AccountID       uuid.UUID
	Date            time.Time
	AmountCents     int64
	Payee           string
	Notes           string
	CategoryID      *uuid.UUID
	TransferGroupID *uuid.UUID
	ImportBatchID   *uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CategoryName    *string
	CategoryKind    *CategoryKind
	CategoryColor   *string
	AccountName     string
	AccountType     AccountType
	AccountCurrency string
}

// Filters are optional: empty/NULL parameters match everything. Rows join
// category and account names for display.
func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.UserID,
		arg.FromDate,
		arg.ToDate,
		arg.AccountID,
		arg.CategoryID,
		arg.Uncategorized,
		arg.Search,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsRow
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.AmountCents,
			&i.Payee,
			&i.Notes,
			&i.CategoryID,
			&i.TransferGroupID,
			&i.ImportBatchID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategoryKind,
			&i.CategoryColor,
			&i.AccountName,
			&i.AccountType,
			&i.AccountCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transactionByID = `-- name: TransactionByID :one
SELECT id, user_id, account_id, date, amount_cents, payee, notes, category_id, transfer_group_id, import_batch_id, dedup_hash, created_at, updated_at FROM transactions WHERE id = $2 AND user_id = $1
`

type TransactionByIDParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) TransactionByID(ctx context.Context, arg TransactionByIDParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, transactionByID, arg.UserID, arg.ID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Date,
		&i.AmountCents,
		&i.Payee,
		&i.Notes,
		&i.CategoryID,
		&i.TransferGroupID,
		&i.ImportBatchID,
		&i.DedupHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET date = $3, amount_cents = $4, payee = $5, notes = $6, category_id = $7,
    dedup_hash = $8, updated_at = now()
WHERE id = $2 AND user_id = $1
RETURNING id, user_id, account_id, date, amount_cents, payee, notes, category_id, transfer_group_id, import_batch_id, dedup_hash, created_at, updated_at
`

type UpdateTransactionParams struct {
	UserID      uuid.UUID
	ID          uuid.UUID
	Date        time.Time
	AmountCents int64
	Payee       string
	Notes       string
	CategoryID  *uuid.UUID
	DedupHash   []byte
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.UserID,
		arg.ID,
		arg.Date,
		arg.AmountCents,
		arg.Payee,
		arg.Notes,
		arg.CategoryID,
		arg.DedupHash,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Date,
		&i.AmountCents,
		&i.Payee,
		&i.Notes,
		&i.CategoryID,
		&i.TransferGroupID,
		&i.ImportBatchID,
		&i.DedupHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
